Repository SainsburyWellcomeCentre/aeon_experiments, pull requests merged in 2024-02, with the labels that each got.

#496 Add timeout notifications for all camera streams
  workflows/social/Extensions/Alerts.bonsai
  workflows/social/Extensions/StreamTimeout.bonsai
Labels: critical, fix

#504 Ensure chunks are closed for text and harp streams
  workflows/social/Extensions/Logging.bonsai
Labels: fix

#505 Add sln to .gitignore
  .gitignore
Labels: AEON3, AEON4, easy / quick

#507 Remove repeat every subject from environment logic
  workflows/social/Extensions/EnvironmentLogic.bonsai
  workflows/social/Extensions/Visualization.bonsai
Labels: fix

#508 Change gain of the patch cameras to match AEON4
  workflows/social/Social-AEON3.bonsai
Labels: fix

#509 Remove unused debugging log
  workflows/social/Extensions/Alerts.bonsai
Labels: fix

#510 Update environment and acquisition packages
  bonsai/Bonsai.config
Labels: feature

#511 Add video stream selector to main control panel
  bonsai/Bonsai.config
  workflows/social/Extensions/ControlPanel.bonsai
  workflows/social/Extensions/StreamSelector.cs
  workflows/social/Social-AEON3.bonsai
  workflows/social/Social-AEON3.bonsai.layout
  workflows/social/Social-AEON4.bonsai
  workflows/social/Social-AEON4.bonsai.layout
  workflows/social/Social-Simulator.bonsai
Labels: feature
